Redesign landing page
Developer-DAO/developerdao.com pull request #159
Opened 2021-11-01 17:44 UTC by Nazeeh21

### What does it do?
Developed the **Developer_Dao** website.

### Any helpful background information?
This PR contains the newly developed **Developer Dao** website according to the [figma](https://www.figma.com/file/NuGyq4CdJaCFAt6oubMcVv/D_D?node-id=7%3A2) design. The newly developed _landing page_ can be found on `/landing-page` route. (This setup is chosen to avoid merge conflicts on the PR).

This is draft PR, so everyone is welcome to give their suggestion. The footer of the website is remained to be redeveloped according to the new design, we'll add this in the upcoming commits.

### Any new dependencies? Why were they added?
marquee library to show the tweets

### Relevant screenshots/gifs
![image](https://user-images.githubusercontent.com/56908732/139715328-bd3787ea-35af-4d94-9aa7-55066aeb1163.png)

### Does it close any issues?
This PR targets fixing issue #114

Closes #114

2021-11-03 16:07 UTC, with-heart commented on src/layout/Page/index.tsx
> +  );
I'm wondering if we want to apply this to the main page only. imo it looks out of place on the other pages

2021-11-04 04:46 UTC, Nazeeh21 commented on src/layout/Page/index.tsx
> +  );
@with-heart yes, I think it should be restricted to the main page only. We'll update that in the next commit.

2021-11-07 13:10 UTC, Nazeeh21 commented on src/layout/Page/index.tsx
> +  );
I've updated the pr restricting background only to the landing page and adding all the components according to the figma design.

2021-11-08 05:25 UTC, Dhaiwat10 commented
Font issues on Firefox & Safari. Works fine on Chrome.

![image](https://user-images.githubusercontent.com/39617427/140688544-332cf9cb-735f-4c1c-8293-09a759ba685c.png)

==============

The `/` route has been affected

![image](https://user-images.githubusercontent.com/39617427/140688648-201ad712-0b1d-4c95-a5eb-277d8d4b7eef.png)

2021-11-08 13:09 UTC, Nazeeh21 commented
> Font issues on Firefox & Safari. Works fine on Chrome.
> 
> ![image](https://user-images.githubusercontent.com/39617427/140688544-332cf9cb-735f-4c1c-8293-09a759ba685c.png)
> 
> ==============
> 
> The `/` route has been affected
> 
> ![image](https://user-images.githubusercontent.com/39617427/140688648-201ad712-0b1d-4c95-a5eb-277d8d4b7eef.png)

We'll fix this font issue for browsers other than chrome.

`/` route is affected as we've removed the dark background from the routes other than `/landing-page`. Do we've to maintain the _old landing page_ as well, if we've to then we'll fix it?

2021-11-10 18:01 UTC, Dhaiwat10 commented
Any updates on this PR? We should look to get the new landing page asap.

@with-heart @narbs91 @codingwithmanny @gjsyme what are you thinking about the new routing once this landing page gets merged? Here is what I am thinking:

- `/` new landing page
- `/token-viewer` the current landing page/search functionality

the rest can stay as it is, I believe.

2021-11-11 04:50 UTC, Nazeeh21 commented
> * `/` new landing page
> * `/token-viewer` the current landing page/search functionality
> 
> the rest can stay as it is, I believe.

This new routing seems perfect. I'll implement it once everyone agrees to this. Thoughts @with-heart @codingwithmanny @narbs91 ?

2021-11-11 04:58 UTC, narbs91 commented
Those routes look good to me gang 🚀

2021-11-11 06:20 UTC, thomasmetta commented
LGTM

2021-11-14 05:46 UTC, with-heart commented
The routes change sounds like a solid plan to me!

Since this has taken longer than I think any of us intended it to, we're going to be sold out of tokens by the time we get this merged (which I'm hoping will be this weekend). I think we need to replace the "Join the future" messaging with the DAO's mission, values, goals, and some content with season 0.

I'll connect with `marc` from the writer's guild in the morning to see if we can get that content from them asap so we can adapt this PR.

2021-11-14 05:57 UTC, Nazeeh21 commented
As everyone has agreed on the routing thing we'll set up that soon.
Replacing the **Join the Future** with season 0's mission, values and goals is an awesome idea and would be a good take looking at the present scenario.

2021-11-15 15:51 UTC, with-heart requested changes
Finally added some thoughts/comments/suggestions to the current implementation. Sorry it took me so long!

We can skip any/all of them or follow up on them at a later point if it would be more convenient!

2021-11-15 15:51 UTC, with-heart commented on src/pages/landing-page.tsx
> +  );
One of the things I think we'd benefit most from here would be to restructure this implementation to use nested `Stack` components to control the spacing between components/elements rather than attaching individual margins.

This approach gives us a lot more flexibility in terms of reusing individual components/elements and adding new components that automatically inherit the `spacing` from the `Stack` rather than having to adjust margins as things are added.

```suggestion
  return (
    <PageLayout>
      <Button
        zIndex={10}
        borderWidth={2}
        bottom="15"
        right="10"
        position="fixed"
        size="md"
        onClick={toggleColorMode}
      >
        {color === '#000' ? <FaMoon /> : <FaSun />}
      </Button>
      <VStack as="main" spacing={24} pt={12}>
        <VStack
          spacing={5}
          color={color}
          mx="auto"
          textAlign="center"
          w="full"
          maxW="3xl"
        >
          <Stack spacing={7} align="center">
            <Text
              fontFamily="poppins"
              fontWeight="light"
              fontSize={{ base: '3xl', md: '6xl', lg: '6xl' }}
            >
              {t('heading')}
            </Text>
            <Text
              px={4}
              fontWeight="400"
              fontSize={{ base: '14px', md: '18px', lg: '18px' }}
              maxW={{ base: '90%', sm: '80%', md: '2xl' }}
            >
              {t('subHeading')}
            </Text>
          </Stack>

          <Stack
            direction={{ base: 'column', sm: 'row', md: 'row', lg: 'row' }}
            spacing={{ base: 6, sm: 30, md: 40, lg: 60 }}
          >
            <Stack spacing={5}>
              <Box display="flex" flexDirection="column" alignItems="center">
                <Text fontSize="4rem" fontFamily="poppins">
                  120<sup style={{ fontSize: '1rem', top: -30 }}>/800</sup>
                </Text>
                <Text fontSize="1rem" color={secondaryColor}>
                  {t('seats')}
                </Text>
              </Box>
              <SuperButton
                title={t('becomeMember')}
                background={'#2128CA'}
                leftIcon={<FaEthereum />}
              />
            </Stack>
            <Stack spacing={5}>
              <Box display="flex" flexDirection="column" alignItems="center">
                <Text fontFamily="poppins" fontSize="4rem">
                  853
                </Text>
                <Text fontSize="1rem" color={secondaryColor}>
                  {t('devsBuilding')}
                </Text>
              </Box>
              <SuperButton
                title={t('joinDiscord')}
                background={'#3F46F3'}
                leftIcon={<FaDiscord />}
              />
            </Stack>
          </Stack>
        </VStack>

        <HStack w="full" background={tweetBackground} gridGap="4">
          <Marquee gradient={false} speed={60} pauseOnHover={true}>
            {tweetData.map((twetter, index) => (
              <Tweet
                key={index}
                tweet={twetter.tweet}
                name={twetter.name}
                userName={twetter.userName}
                profileSrc={twetter.profileImg}
              />
            ))}
          </Marquee>
        </HStack>

        <JoinFuture />
      </VStack>
    </PageLayout>
  );
```

Unfortunately the diff here isn't great so it's hard to see what changed. I'll list some of them out:

- Removed all `margin`-related props
- Moved `Button` outside of `PageLayout` since its position is `fixed`. If it was inside `PageLayout`, it messed with the margins attached by `spacing`
  - Attached `pt={12}` instead of using margin
- Converted `chakra.main` into `VStack` with `spacing={24}`
- Added a stack around `heading` and `subHeading`
- Converted "seats left"/"devs building" to `Stack` components

2021-11-15 15:51 UTC, with-heart commented on src/pages/landing-page.tsx
> +  );
One of the things I think we'd benefit most from here would be to restructure this implementation to use nested `Stack` components to control the spacing between components/elements rather than attaching individual margins.

This approach gives us a lot more flexibility in terms of reusing individual components/elements and adding new components that automatically inherit the `spacing` from the `Stack` rather than having to adjust margins as things are added.

```suggestion
  return (
    <PageLayout>
      <Button
        zIndex={10}
        borderWidth={2}
        bottom="15"
        right="10"
        position="fixed"
        size="md"
        onClick={toggleColorMode}
      >
        {color === '#000' ? <FaMoon /> : <FaSun />}
      </Button>
      <VStack as="main" spacing={24} pt={12}>
        <VStack
          spacing={5}
          color={color}
          mx="auto"
          textAlign="center"
          w="full"
          maxW="3xl"
        >
          <Stack spacing={7} align="center">
            <Text
              fontFamily="poppins"
              fontWeight="light"
              fontSize={{ base: '3xl', md: '6xl', lg: '6xl' }}
            >
              {t('heading')}
            </Text>
            <Text
              px={4}
              fontWeight="400"
              fontSize={{ base: '14px', md: '18px', lg: '18px' }}
              maxW={{ base: '90%', sm: '80%', md: '2xl' }}
            >
              {t('subHeading')}
            </Text>
          </Stack>

          <Stack
            direction={{ base: 'column', sm: 'row', md: 'row', lg: 'row' }}
            spacing={{ base: 6, sm: 30, md: 40, lg: 60 }}
          >
            <Stack spacing={5}>
              <Box display="flex" flexDirection="column" alignItems="center">
                <Text fontSize="4rem" fontFamily="poppins">
                  120<sup style={{ fontSize: '1rem', top: -30 }}>/800</sup>
                </Text>
                <Text fontSize="1rem" color={secondaryColor}>
                  {t('seats')}
                </Text>
              </Box>
              <SuperButton
                title={t('becomeMember')}
                background={'#2128CA'}
                leftIcon={<FaEthereum />}
              />
            </Stack>
            <Stack spacing={5}>
              <Box display="flex" flexDirection="column" alignItems="center">
                <Text fontFamily="poppins" fontSize="4rem">
                  853
                </Text>
                <Text fontSize="1rem" color={secondaryColor}>
                  {t('devsBuilding')}
                </Text>
              </Box>
              <SuperButton
                title={t('joinDiscord')}
                background={'#3F46F3'}
                leftIcon={<FaDiscord />}
              />
            </Stack>
          </Stack>
        </VStack>

        <HStack w="full" background={tweetBackground} gridGap="4">
          <Marquee gradient={false} speed={60} pauseOnHover={true}>
            {tweetData.map((twetter, index) => (
              <Tweet
                key={index}
                tweet={twetter.tweet}
                name={twetter.name}
                userName={twetter.userName}
                profileSrc={twetter.profileImg}
              />
            ))}
          </Marquee>
        </HStack>

        <JoinFuture />
      </VStack>
    </PageLayout>
  );
```

Unfortunately the diff here isn't great so it's hard to see what changed. I'll list some of them out:

- Removed all `margin`-related props
- Moved `Button` outside of `PageLayout` since its position is `fixed`. If it was inside `PageLayout`, it messed with the margins attached by `spacing`
  - Attached `pt={12}` instead of using margin
- Converted `chakra.main` into `VStack` with `spacing={24}`
- Added a stack around `heading` and `subHeading`
- Converted "seats left"/"devs building" to `Stack` components

2021-11-15 15:51 UTC, with-heart commented on src/components/JoinFuture/index.tsx
> +  );
Following along with the `Stack`-based refactor, I removed all `margin`-related props here:

```suggestion
  return (
    <VStack spacing={6} color={color} mx="auto" textAlign="center" w="full">
      <VStack>
        <Image w={10} h="auto" src="/rocket.png" alt="rocket" />
        <Text
          fontFamily="poppins"
          fontWeight="light"
          fontSize={{ base: '3xl', md: '6xl', lg: '6xl' }}
        >
          {t('future')}
        </Text>
        <Text
          px={4}
          fontWeight="400"
          color={secondaryColor}
          fontFamily="inter"
          fontSize={{ base: '14px', md: '18px', lg: '18px' }}
          maxW={{ base: '90%', sm: '80%', md: '2xl' }}
        >
          {t('member')}
        </Text>
      </VStack>
      <Grid
        templateColumns={{
          base: 'repeat(1, 1fr)',
          md: 'repeat(2, 1fr)',
          xl: 'repeat(4, 1fr)',
        }}
        gap={4}
        w={{ base: 'full', md: '80%', lg: '90%' }}
        justifyItems="center"
        mx="auto"
      >
        {Features.map((feature, index) => (
          <Feature
            key={index}
            imgSrc={feature.imgSrc}
            title={feature.title}
            description={feature.description}
          />
        ))}
      </Grid>
      <SuperButton
        title={t('becomeMember')}
        background={'#2128CA'}
        leftIcon={<FaEthereum />}
      />
    </VStack>
  );
```

2021-11-15 15:51 UTC, with-heart commented on src/components/Feature/index.tsx
> +  );
And finally I replaced `margin`-related props in here:

```suggestion
  return (
    <Stack
      spacing={4}
      fontFamily="inter"
      width={{ base: '80%', md: '100%', xl: '17rem' }}
      textAlign="left"
      p="6"
      rounded="md"
      // bg={bgColor}
    >
      <Box>
        <Image src={imgSrc} alt={imgSrc} />
      </Box>
      <Text fontSize="md" fontWeight="bold">
        {title}
      </Text>
      <Text color={color}>{description}</Text>
    </Stack>
  );
```

I had to wrap `Image` with `Box` because otherwise it was stretching to massive proportions.

2021-11-15 15:51 UTC, with-heart commented on src/components/JoinFuture/index.tsx
> +        gridGap={4}
`justify-items` controls the placement of grid item content within its grid item container. So `justifyItems="center"` will automatically center the content inside each item.

```suggestion
        gridGap={4}
        justifyItems="center"
```

The outcome is the same as using `mx="auto"` on each `Feature`, but makes the `Feature` component more flexible (like if we wanted to reuse it somewhere else but without it being centered).

2021-11-15 16:44 UTC, Nazeeh21 commented
Thanks for suggesting the changes, we'll implement these changes soon.

2021-11-15 17:41 UTC, with-heart commented
I think something we also need to consider is how we want to style the `SuperButton`. The default color looks great but we need to also define colors for `hover` and `active` states, which I don't think we have access to.

I think we have two paths:

- go with the default `Button` for now with `colorScheme="blue"` or `colorScheme="purple"` which doesn't look quite right, but at least gives us accessible colors in each state
- define a new `theme.colors` scale (`50`-`900`) and use that in combination with the `chakra` factory function to override the default padding on `Button` to achieve the same effect

2021-11-16 05:25 UTC, Nazeeh21 commented
I think we should go with the default `Button` for now by using `colorScheme="blue"`

2021-11-17 07:21 UTC, Nazeeh21 commented
We've implemented all the changes discussed so far other than the font issues on browsers other than chrome.
We'll fix that font issue soon in the upcoming commits.

2022-01-18 06:31 UTC, closed without merging

2022-01-18 20:27 UTC, Dhaiwat10 commented
F

2022-01-18 20:47 UTC, narbs91 commented
> F

F