Add hook to get the DEV NFT supply
Developer-DAO/developerdao.com pull request #160
Opened 2021-11-02 17:15 UTC by embiem

Note: Adding PR as draft, as I still need to finalize the tests, but wanted to share the actual hook already.

### What does it do?

Adds a hook into a new src/hooks/ folder that fetches stats about the DEV NFT supply. Can be used in the PR #159 to retrieve the "seats left" stat, but also just to improve UX on the mint page.

### Any helpful background information?

After seeing the landing-page redesign in #159, I wanted to contribute to it by writing this hook. If necessary, I can also tackle a similar hook to retrieve Discord stats.

### Any new dependencies? Why were they added?

@testing-library/react-hooks, to properly test the hook.

### Relevant screenshots/gifs

-

### Does it close any issues?

Nope.

2021-11-02 21:27 UTC, embiem commented on src/hooks/useDevNFTSupply.ts
> +          ),
This will create a lot of requests, but it's the only way I found to do this. 

web3 library has [BatchRequests](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#batchrequest), which would lower the number of requests but increase the overall execution time as they're called sequentially instead.

Anyways, if anyone knows of a better way to do it, please let me know :-)

2021-11-02 23:01 UTC, embiem commented
I just pushed my latest changes. I'll stop now as it is getting bigger than I initially wanted it to. The original PR description has been edited to reflect the current changes.

In this PR, I now also included a suggestion to use typechain. This adds types that are generated via CLI (see the `postinstall` script), are git-ignored and can be used to get a typed ethers contract object. An example where types like this are useful (apart from auto-completion): changing `contract.totalSupply()` to `contract.functions.totalSupply()` will change the `BigNumber` response to `Array<BigNumer>`. Without types, an error like this could sneak through all the way to runtime.

I'd love to get your feedback on this suggestion.

2021-11-03 05:32 UTC, narbs91 commented on src/hooks/useDevNFTSupply.ts
> +    const fetchLockedSupply = async () => {
If i understood the intent of this function it seems like we're fetching the locked supply so we can calculate the remaining tokens available for mint.  Since we know for a fact that there are 8000 total tokens, 3 reserved for the owner and not counting the 0 address, can we just not just do:  `availToMint = 8000 - 3 -1 - totalSupply`?  As totalSupply is the count of the currently minted NFT's

2021-11-03 05:34 UTC, narbs91 commented on src/hooks/useDevNFTSupply.ts
> +    const fetchLockedSupply = async () => {
Now the only thing i'm not super clear about is if totalSupply is deduped per address and thus represents the number of unique owners

2021-11-03 05:51 UTC, narbs91 commented on src/hooks/useDevNFTSupply.ts
> +    const fetchLockedSupply = async () => {
Just did the math 8000-222-1- 4887 = 2,889 which is the actual number of tokens left; however the UI looks like it 's counting the zero address to in it's calculations as it's showing 2890 when i landed on it

2021-11-03 05:57 UTC, narbs91 commented on src/hooks/useDevNFTSupply.ts
> +    const fetchLockedSupply = async () => {
oh nvm, just re-read and this is for the locked supply (DOH!) but i suppose this raises another thought around does the end user actually need to know this information?  Like as a person who wants to join the DAO I only really care if there's tokens available for me to mint (i.e the public supply) and not so much the tokens only available to the owner.

2021-11-03 14:26 UTC, with-heart requested changes
I love the thinking here! A library of general-purpose hooks make for a solid foundation for an app.

2021-11-03 14:26 UTC, with-heart commented on .gitignore
> +/types/ethers-contracts
Would we not want to check these in? If the types are used throughout the codebase, they should remain a part of it.

2021-11-03 14:26 UTC, with-heart commented on src/hooks/useDevNFTSupply.ts
> +    loading: totalSupply === -1 || lockedSupply === -1,
This might just be personal preference here but I'd like to suggest that we rename this to `isLoading`. That naming follows a convention used by a number of other libraries ([Chakra UI](https://chakra-ui.com/docs/form/button#button-loading-state), [`react-query`](https://react-query.tanstack.com/guides/queries)) and prefixing variables with `is`/`has`/`are` makes it obvious at a glance that the variable is a `boolean` without needing to check the type signature.

2021-11-03 23:00 UTC, embiem commented on src/hooks/useDevNFTSupply.ts
> +    const fetchLockedSupply = async () => {
Yes I agree with you. When getting the totalSupply() via the one function call on the contract we get the supply of public & locked tokens, so even if we want to show the correct number of available public tokens we'd still need to know what portion of the total supply is actually locked.

2021-11-03 23:04 UTC, embiem commented on .gitignore
> +/types/ethers-contracts
Fair point. I usually don't include any generated files in git, so that's why I put it on the git-ignore list initially.

2021-11-03 23:04 UTC, embiem commented on src/hooks/useDevNFTSupply.ts
> +    loading: totalSupply === -1 || lockedSupply === -1,
Agreed! I'll change it.

2021-11-03 23:14 UTC, embiem commented on src/hooks/useDevNFTSupply.ts
> +    const fetchLockedSupply = async () => {
I just saw that DennisKo used `contract.queryFilter` in #158 to get all transactions and retrieve all available tokens this way. Not sure whether this might be the better approach to fetch how many of the locked tokenIds were already minted.

Alternatively I was thinking that this must be the kind of info that The Graph is trying to index. Should be more efficient to actually index this info instead of always calling the contract's read functions. I have 0 experience with The Graph yet, though.

2021-11-03 23:39 UTC, embiem commented on src/hooks/useDevNFTSupply.ts
> +    const fetchLockedSupply = async () => {
> Like as a person who wants to join the DAO I only really care if there's tokens available for me to mint (i.e the public supply) and not so much the tokens only available to the owner.

That's the number I show on the /mint page. It's returned as the `remainingPublicSupply`, which is `PUBLIC_MAX_SUPPLY - (totalSupply - lockedSupply)`.

2021-11-04 04:24 UTC, narbs91 commented on src/hooks/useDevNFTSupply.ts
> +    const fetchLockedSupply = async () => {
It might worthwhile to poke around using the `contract.queryFilter` to see if we can cut down on the number of network calls (haven't had any experience using this myself so can't say for sure it'll work).  With regards to The Graph, i think you're right that it probs has the info indexed already but querying against a subgraph costs money so i don't know if it's a viable solution in our current stage of the DAO

2021-11-04 12:41 UTC, with-heart approved these changes

2021-11-04 16:42 UTC, embiem commented
Thanks for approving @with-heart! I do have one more thing in the pipe though, based on @narbs91's comment to try out `contract.queryFilter` and my Discord message where everyone is saying we should display the amount of unique token holder addresses instead of the total supply.

2021-11-05 20:57 UTC, embiem commented
I just added the final commit, please let me know if there's any more feedback on this.

2021-11-06 06:13 UTC, narbs91 commented on src/hooks/useDevNFTSupply.ts
> +    remainingTotalSupply: MAX_SUPPLY - totalSupply,
[nit pick] do we need to return `remainingTotalSupply` and `remainingLockedSupply` if we're not using them upstream?  Or did you leave here incase we wanted to use them in the future?

2021-11-06 06:15 UTC, narbs91 approved these changes
LGTM!  Made a minor comment on some of the return elements in useDevNFTSupply but other then that it looks great, awesome job

2021-11-06 08:20 UTC, embiem commented on src/hooks/useDevNFTSupply.ts
> +    remainingTotalSupply: MAX_SUPPLY - totalSupply,
Yes I left them for any peobable future use, but I can see how this might add bloat when we do this a lot. So I'd be happy to remove as well.

2021-11-07 05:08 UTC, narbs91 commented on src/hooks/useDevNFTSupply.ts
> +    remainingTotalSupply: MAX_SUPPLY - totalSupply,
Nah, we can keep them here for now all good

2021-11-07 05:08 UTC, merged

2021-11-09 02:05 UTC, narbs91 commented
@allcontributors please add @embiem  for code