Add a Resources page
Developer-DAO/developerdao.com pull request #161
Opened 2021-11-03 05:29 UTC by gjsyme

### What does it do?
Pulls data from the Airtable resource base to populate a list of cards that people can view right from the developerdao.com website.

### Any helpful background information?
This is identified as our lowest hanging of educational fruits and something that we want to get out rapidly.

### Any new dependencies? Why were they added?
`airtable`; this provides support for the Airtable API so that we can fetch the data.

### Relevant screenshots/gifs
Deferred until someone can take a swipe and cleaning up the UI.

### Does it close any issues?
No

### New keys have been created
New i18n keys will require translations for all languages other than english

2021-11-03 14:08 UTC, with-heart requested changes

2021-11-03 14:08 UTC, with-heart commented on src/utils/AirtableResourceClasses.ts
> +// simplified airtable objects that work for our purposes
Could we rename this to `src/types/airtable.ts`? These aren't really `utils` 😁

2021-11-03 14:08 UTC, with-heart commented on src/pages/resources.tsx
> +function KnowledgeBase(props: { airtable: Airtable }) {
`props` aren't actually used!

```suggestion
function KnowledgeBase() {
```

2021-11-03 14:08 UTC, with-heart commented on src/pages/resources.tsx
> +  useEffect(() => {
imo we could add a lot of clarity here by separating the airtable stuff out into a hook. That way someone wanting to understand what the component is rendering can just look at its body (which will be quite short) and if they want to dig deeper into the complexity of how we're managing the airtable data, they can then read through the hook. 

```tsx
const useKnowledgeBase = () => {
  // `useTranslation`, `useToast`, `useState`, and `useEffect` calls
  return viewList
}

const KnowledgeBase = () => {
  const knowledge = useKnowledgeBase()
  return (
    {knowledge.map(item => {
      // cool stuff here or whatever
    }}
  )
}
```

2021-11-03 14:08 UTC, with-heart commented
This is gonna be so nice to have!

2021-11-04 02:57 UTC, gjsyme commented on src/components/ResourceCard/index.tsx
> +  };
React objected to me returning a string as a component so I have taken the middle path of making a MediaButton that builds the entire button (including a MediaIcon as componentized above and the text being determined by a method in the MediaButton).

2021-11-04 03:44 UTC, narbs91 commented on src/components/ResourceCard/index.tsx
> +// const MediaText = ({mediaType}: {mediaType: string}) => {
[nit pick] Did you mean to leave this commented code here?

2021-11-04 03:44 UTC, narbs91 commented on src/components/ResourceCard/index.tsx
> +        {/* <Box>{getAuthor(kbRecord.extendedAuthors)}</Box> */}
[nit pick] ditto here around commented code

2021-11-04 03:46 UTC, narbs91 commented on src/pages/resources.tsx
> +      !authorList.length ||
might be cleaner to put this in it's own private function?

2021-11-04 03:47 UTC, narbs91 commented on src/pages/resources.tsx
> +    : resourceBaseList.filter((item) => item.fields.Curated);
Can item.fields ever be null || undefined?  If so maybe we can add a check here around it (i think you can do `item.fields?.Curated` if i'm not mistaken"

2021-11-04 03:54 UTC, narbs91 commented on src/components/ResourceCard/index.tsx
> +          <Link href={kbRecord.Source} _hover={undefined}>
Just curious, why do we have the `_hover={undefined}` here?  Mostly around the `undefined` lol

2021-11-04 03:57 UTC, narbs91 commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_READONLY_KEY = 'keyDaaDlZelNrerXQ';
Is this key something that has to be paid for or has a rate limit applied to?  I'd push for us to have this as an env variable as we should strive not to expose apiKeys or what not in a public repo.   I can add an env variable in vercel for this entry:  NEXT_PUBLIC_AIRTABLE_READONLY_KEY and then you can access it like `process.env.NEXT_PUBLIC_AIRTABLE_READONLY_KEY`

2021-11-04 03:58 UTC, narbs91 commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_READONLY_KEY = 'keyDaaDlZelNrerXQ';
I've added this env variable in vercel for the readonly key

2021-11-04 03:59 UTC, narbs91 commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_RESOURCE_BASE = 'appPP6MpO5hrfQwqI';
Not sure what this is for but we can take the same approach if this is something that shouldn't be out in public

2021-11-04 04:01 UTC, narbs91 commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_RESOURCE_BASE = 'appPP6MpO5hrfQwqI';
Eh i added this one too to vercel:  NEXT_PUBLIC_AIRTABLE_RESOURCE_BASE

2021-11-04 04:50 UTC, gjsyme commented on src/components/ResourceCard/index.tsx
> +// const MediaText = ({mediaType}: {mediaType: string}) => {
I did when I did it and then forget to clean it up afterwards. Thanks!

2021-11-04 04:57 UTC, gjsyme commented on src/pages/resources.tsx
> +    : resourceBaseList.filter((item) => item.fields.Curated);
Looked into this as the assumption of fields being non-falsey is a lot of places. The airtable sdk has ```setRawJson(rawJson: RecordJson): void {
        this._rawJson = rawJson;
        this.fields = (this._rawJson && this._rawJson.fields) || {};
    }```
    which seems to be the way they update a Record's data -> we'll always at least have a fields object.

2021-11-04 05:00 UTC, gjsyme commented on src/components/ResourceCard/index.tsx
> +          <Link href={kbRecord.Source} _hover={undefined}>
Seems useless. Was in the sample I made on links-as-buttons in chakra but doesn't seem to change behavior.

2021-11-04 05:02 UTC, gjsyme commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_READONLY_KEY = 'keyDaaDlZelNrerXQ';
Perhaps worth coordinating with @kempsterrrr and then replacing it behind the scenes. 
There is a rate limit: 
```RATE LIMITS
The API is limited to 5 requests per second per base. If you exceed this rate, you will receive a 429 status code and will need to wait 30 seconds before subsequent requests will succeed.

The official JavaScript client has built-in retry logic.

If you anticipate a higher read volume, we recommend using a caching proxy. This rate limit is the same for all plans and increased limits are not currently available.```

2021-11-04 05:04 UTC, gjsyme commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_RESOURCE_BASE = 'appPP6MpO5hrfQwqI';
What's the solution for production using the vercel-set value and non-production using the locally defined variable?

2021-11-04 05:07 UTC, gjsyme commented
Where we want this to be a public good, I think we need to figure out the caching proxy they refer to as people would be loading that every day. I'm going to say that's a "new issue" kind of problem though.

2021-11-04 05:08 UTC, narbs91 commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_RESOURCE_BASE = 'appPP6MpO5hrfQwqI';
So production would be covered by the variable being set in vercel but for non-prod (basically locally) the solution is to add a `.env` file to the project root and add the key/value there.  This is something that we won't want people to commit and it's already in the `.gitignore` if i'm not mistaken.  We can push up a sample.env though that has the keys but not the values and have people ask for the values from one of us.  Though the issue then becomes who do we give the secret too and who do we not which is probs a process we have to come up with

2021-11-04 05:11 UTC, narbs91 commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_READONLY_KEY = 'keyDaaDlZelNrerXQ';
ah i see, i guess it really depends on the traffic we get on the page; however, if the content is fairly static in nature we could always look to introduce some caching on our end (separate issue obviously)

2021-11-04 05:15 UTC, gjsyme commented on src/pages/resources.tsx
> +      !authorList.length ||
I don't agree where it's a one-time block. I may be wrong, but it seems like just moving that block of or statements around if we make it a function.

2021-11-04 05:16 UTC, gjsyme commented
I opened an issue for the caching proxy #166 as it will resolve the question of exposing keys anyway (proxy would have to have them; queries will go there vice direct to airtable).

2021-11-04 11:55 UTC, with-heart commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_RESOURCE_BASE = 'appPP6MpO5hrfQwqI';
`.env.local` instead of `.env` :)

2021-11-06 05:32 UTC, gjsyme commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_READONLY_KEY = 'keyDaaDlZelNrerXQ';
@narbs91 if you can update the constants to be server side, then we're good to go on this. the work by @Neumand on my fork lets us make the call to airtable on the server side (and restrict how often it will refresh) so we dont' even need NEXT_PUBLIC_

2021-11-06 05:33 UTC, gjsyme commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_RESOURCE_BASE = 'appPP6MpO5hrfQwqI';
see above - server side constants work (same names, just no 'NEXT_PUBLIC_')

2021-11-06 05:48 UTC, narbs91 commented on src/utils/DeveloperDaoConstants.ts
> +export const AIRTABLE_READONLY_KEY = 'keyDaaDlZelNrerXQ';
Cool beans, i'll change them up to remove the NEXT_PUBLIC prefix

2021-11-06 05:51 UTC, narbs91 commented on src/lib/airtable.ts
> +    blockchainMap[item.id] = item.fields.Name;
is it possible for `item.fields` to be null or undefined?

2021-11-06 05:52 UTC, narbs91 commented on src/lib/airtable.ts
> +      ...(resource.fields.Author?.length < 0 && {
Same question here around the possibility of `resource.fields` being null or undefined

2021-11-06 05:58 UTC, narbs91 commented on src/pages/resources.tsx
> +            <Text>No Records</Text>
Looks like we missed this piece of text getting added to the translation files

2021-11-06 06:00 UTC, narbs91 commented on src/utils/useAirtableResources.ts
> +      process.env.NEXT_PUBLIC_AIRTABLE_KEY &&
We change these guys removing `NEXT_PUBLIC` since i changed them up on vercel

2021-11-06 06:09 UTC, gjsyme commented on src/utils/useAirtableResources.ts
> +      process.env.NEXT_PUBLIC_AIRTABLE_KEY &&
That file is out anyway to do the caching. See brand new PR :grin:

2021-11-06 06:09 UTC, gjsyme commented on src/utils/useAirtableResources.ts
> +      process.env.NEXT_PUBLIC_AIRTABLE_KEY &&
Err. Commit. Whatever. If you've done your work already then I'm going to move it to a real PR.

2021-11-06 06:13 UTC, gjsyme commented on src/lib/airtable.ts
> +    blockchainMap[item.id] = item.fields.Name;
believe this was a previous comment, and no, airtable sdk will create an empty object if there's nothing found (from what i found in their source that I think i pasted into that question)

2021-11-06 06:17 UTC, narbs91 commented on src/utils/useAirtableResources.ts
> +      process.env.NEXT_PUBLIC_AIRTABLE_KEY &&
i've had my run through with it, if you're good to go we can turn it into a for realz PR hehe

2021-11-06 06:22 UTC, gjsyme commented on src/utils/useAirtableResources.ts
> +      process.env.NEXT_PUBLIC_AIRTABLE_KEY &&
ehhh it's failing on proptypes

2021-11-07 06:16 UTC, narbs91 commented
So i took a look at the props code you were mentioning Discord @gjsyme and didn't see anything that stood out as "bad" in my eyes. The way you did it is the same way i would have done it wrt to the typing.

As an aside i was messing around with the Ui a bit and landed on something that looks like this:

Desktop

![image](https://user-images.githubusercontent.com/29411347/140634448-41b317a6-d4b3-4daf-bd64-916cb7a5272f.png)

Mobile

![image](https://user-images.githubusercontent.com/29411347/140634578-a5e6babe-e23c-4098-8c78-0dd839ec74e4.png)


Basically i slimmed it down to the bare essentials and used a nifty [url preview library](https://www.npmjs.com/package/@dhaiwat10/react-link-preview) our friend @Dhaiwat10 created 🔥 🔥 🔥 

I think it's cleaner and gives it a bit of lipstick to stand out though the direction for it is totally still up in the air

2021-11-07 06:17 UTC, narbs91 commented
Plus later on we can also introduce a search bar uptop where we can search via the tags (where i've clumped the categories and tags together in the above screenshots)

2021-11-07 06:21 UTC, narbs91 commented
I don't think i can push onto your branch but this is the code I adjusted in `ResourceCard/index.tsx` to get it to look like the above (rough code that still needs a bit of styling applied to look the very best):

(need to `yarn add @dhaiwat10/react-link-preview`)

```javascript
import { LinkPreview } from '@dhaiwat10/react-link-preview';
....
function KnowledgeCard(props: { data: Resource }) {
  const { t } = useTranslation();

  const kbRecord = props.data.fields;

  return (
    <WrapItem maxW={{ base: '100%', md: '800px' }}>
      <VStack>
        <LinkPreview
          url={kbRecord.Source}
          width="500px"
          height="500px"
          descriptionLength={250}
        />
        <Author authors={kbRecord.extendedAuthors} />
        <HStack>
          {kbRecord.Category ? <Tag>{kbRecord.Category}</Tag> : null}
          {kbRecord.Tags?.map((tag: string, index: number) => (
            <Badge key={`tag-${index}`}>{tag}</Badge>
          ))}
          <LevelBadge levelName={kbRecord.Level} />
        </HStack>
      </VStack>
    </WrapItem>
  );
}
```

2021-11-07 06:23 UTC, narbs91 commented
Oh looks like i can push, sweet hehe

2021-11-08 00:26 UTC, gjsyme commented
This is great. The visuals definitely needed some love and I think this fits the bill. I agree that filtering needs to be added down the road but I'd like to see this go live ASAP so I'm not worrying about it yet.

2021-11-08 01:08 UTC, narbs91 commented
> This is great. The visuals definitely needed some love and I think this fits the bill. I agree that filtering needs to be added down the road but I'd like to see this go live ASAP so I'm not worrying about it yet. It might be nice to have a filler for those that don't have a visual in the cards.

Sweet, glad you like it :), yeah the filter is more of a nice to have atm but the overall page is good enough (minus some styling) for a MVP.  That's a good question around the default image, i don't know how to do that but maybe @Dhaiwat10 can give us the super secret details 👀

2021-11-08 01:27 UTC, narbs91 commented
@gjsyme did you want me to help out with the styling and default image or are you going to take it over the finish line?

2021-11-08 03:15 UTC, narbs91 commented
@gjsyme added the styling to the page and some stuff around a11y; however, didn't figure out the default image yet (not that i'm stuck just didn't have the time to dig into it)

2021-11-08 12:42 UTC, Dhaiwat10 commented
Yoo you guys are using my library? 😂 Love that

2021-11-08 12:48 UTC, Dhaiwat10 commented
I spotted some weird blank images too. It's been a long time since I looked into my library's source code. I'm gonna have a look at it & push a patch

2021-11-08 12:48 UTC, Dhaiwat10 commented
Awesome work btw, love the look of this already!

2021-11-08 18:08 UTC, kempsterrrr commented
❤️  that this is being worked on already !! Can I suggest we don't show the un-curated view publicly just incase something makes it in there we really don't want going out on our website 😨 

Are y'all planning to include a way to filter/organise/group the resource to make it easier for users to find what they are looking for? I think that's important if we're going to push something out otherwise I 'd worry that it's not going to address the problem the resource base seeks to address - making it easier to find content you need.

2021-11-09 01:28 UTC, narbs91 commented
> Yoo you guys are using my library? 😂 Love that

It was too good an opportunity to pass up using a D_D members library to spice up the website plus i really digged it anyways lol

2021-11-09 01:35 UTC, narbs91 commented
> ❤️ that this is being worked on already !! Can I suggest we don't show the un-curated view publicly just incase something makes it in there we really don't want going out on our website 😨
> 
> Are y'all planning to include a way to filter/organise/group the resource to make it easier for users to find what they are looking for? I think that's important if we're going to push something out otherwise I 'd worry that it's not going to address the problem the resource base seeks to address - making it easier to find content you need.

I think it's pretty straight forward to default to the un-curated list but TBH i don't really know what curated means.  It could mean that it's curated to my liking which could signal that somehow the website has gotten a hold of my data and curating a list of articles (which isn't the case).  Basically we don't want to give the wrong impression to people (though i may be over exaggerating on my part :P)

With regards to filtering, I do believe @gjsyme and I may have spoken on the side about it but it's definitely on the radar.  On top of that, atm it would seem we're fetching the world from airtable and displaying it on the site; however, i don't think that's going to work in the long term with the amount of article churn we're expecting in the upcoming seasons.  Basically the page performance will take a hit when the load starts to increase and result in a negative user experience. We should think about introducing either pagination or a load more button with a cap of how many results per-fetch we do.

2021-11-09 04:54 UTC, gjsyme commented
We previously had the notion of draft or the like, which was meant for standing between a new submission and going live. That seems to no longer be the case. If our only means of filtering is the Curated boolean, then I agree, we should only have those which have been curated go on the page.
Filtering on the page, to me, makes the most sense for limiting number of views (in part because our API query is simple for the purposes of caching).

2021-11-09 06:10 UTC, gjsyme commented
I worked in the recommendations from @narbs91 (if you had put those changes on something, I couldn't find them) and called in @Dhaiwat10 's package / opened an issue for him to resolve the not-falsey but also not-functional responses that the proxy sometimes gets.
This does have the potential to jam us if the not-for-production proxy doesn't work out. Airtablle has some pictures worked in, but I'm not sure if this counts against our image calls. If so, would be something to proxy for a very long time (assuming vercell would hold that much data).

2021-11-09 16:34 UTC, Dhaiwat10 commented
Hey. I just released a new version of the package and in the latest version you can pass in the fallback image src like this:

```
<LinkPreview url='someurl' fallbackImageSrc='src-to-your-image' />

2021-11-10 00:38 UTC, kempsterrrr commented
> I think it's pretty straight forward to default to the un-curated list but TBH i don't really know what curated means

At the moment this is just a manual step in Airtable where we're explicitly accepting that something shows up in the public view. It's here to make sure we maintain a base layer of quality of the resources being included and also that nothing NSFW or in any other way harmful makes it into the the list. IMHO the curated view is the only view that should ever be public and the end user shouldn't even be need to be aware there is a difference between curated and not curated.

Regarding filtering/organising etc. this info on the page, maybe the benchmark should be what is provided out of the box from the Airtable views:

- List: https://airtable.com/shrzgqiMiHE18Iy9O/tbljejdzelezqT0W7
- Grid: https://airtable.com/shrM4PglRR3BAs3T9

I.e. people should be able to filter based on all the available data points and potentially free text search as well. That said, rather than asking them to do that we could alternatively have a structure to the page that groups content together.

Terrible implementation but something like:

- ethereum
  - beginner 
  - intermediate
  - advanced
- Solana
  - beginner 
  - intermediate
  - advanced

I appreciate that is a non-trivial task. Maybe whilst working on something more custom embedding the Airtable public view that gives those out of the box is a good interim solution.

See example below the fold on this website - https://blockchain-comparison.com/blockchain-protocols/

2021-11-10 00:57 UTC, gjsyme commented
I feel like the default airtable view looks like the 90s wants its excel back. I'm down to continue working on making something web-worthy.
Can any of this be moved to a "fast follow" to borrow a term someone was throwing out on a voice call? Right now we have nothing in place.

2021-11-10 01:30 UTC, narbs91 commented
I think we can probably table the search/filter to a new issue as a fast follow and call the curated list as the MVP.  Filtering is always a bit of cluster to get get "right so it'll require some brainstorming on our end

2021-11-10 05:15 UTC, gjsyme commented
Working through abusing the patience of @Dhaiwat10 as a very needy customer, but also making some iterative improvements as we go. @kempsterrrr the ability to view the non-curated data has been removed.

I'd be open to any "this is the way" type examples of how to filter from a list, but I'm just thinking generate a set of buttons/tags that you can click-to-toggle based upon the values associated with the curated resources.

2021-11-10 12:33 UTC, Neumand commented
@gjsyme I stumbled across a pretty cool dev portfolio last night that implements the filtering based on the button/tags idea.

See: https://theodorusclarence.com/library

It’s open-source so feel free to check out the implementation.

2021-11-11 09:02 UTC, Dhaiwat10 commented
Just had a look at the Vercel deployment. Looking good!

2021-11-11 19:11 UTC, narbs91 commented
Looks good so far to me visually too, just some minor styling things wrt to padding on the titles and patching up mobile view a bit:

![image](https://user-images.githubusercontent.com/29411347/141355143-5d2ed8ef-7f61-49ba-a3c5-00f0a2b13faa.png)


Haven't had a chance to look at the code yet but will try to make some time to have a look through today

2021-11-16 02:05 UTC, narbs91 commented on src/components/ResourceCard/index.tsx
> +            <Link href={`https://twitter.com/${author.twitter}`}>
I would say to add the `isExternal` prop here too to let the user know they'll have a new window open

2021-11-16 02:05 UTC, narbs91 commented on src/components/ResourceCard/index.tsx
> +    <Text>Image Unavailable</Text>
[nit pick] these should be in the loc file

2021-11-16 02:08 UTC, narbs91 commented on src/components/ResourceCard/index.tsx
> +      {/* <VStack minW={{base: '300px'}} maxW={{base: '100%', md: '300px'}}> */}
[nit pick] commented out code

2021-11-16 02:08 UTC, narbs91 commented on src/components/ResourceCard/index.tsx
> +      <VStack w={{ base: '100%', sm: '30em', md: '300px' }}>
Is there a reason we're mixing and matching units here?

2021-11-16 02:14 UTC, gjsyme commented on src/components/ResourceCard/index.tsx
> +      <VStack w={{ base: '100%', sm: '30em', md: '300px' }}>
i believe that the intent was to match the chakra measure of how large a sm screen was as 100% wasn't achieving the desired effect. but it's been a few days so there may be some data loss

2021-11-16 02:16 UTC, narbs91 commented on src/types/airtable.ts
> +    'Developer DAO Member': boolean;
I've never seen this style of syntax before, was there a special reason you went this route versus a regular variable declaration?

2021-11-16 02:19 UTC, narbs91 commented on src/components/ResourceCard/index.tsx
> +            <Link href={`https://twitter.com/${author.twitter}`}>
As well as a span with a visually hidden text that notifies a screen reader what this link represents and that it'll open in another window.  You can add this to the global.css file:

```javascript
.visuallyhidden {
  clip: rect(0, 0, 0, 0);
  clip-path: inset(50%);
  height: 1px;
  width: 1px;
  padding: 0;
  overflow: hidden;
  position: absolute !important;
  white-space: nowrap;
}
```

Then we can progressively add this type of thing to the other links we have as things go forward

2021-11-16 02:19 UTC, narbs91 commented on src/lib/airtable.ts
> +// const airTable = new Airtable({ apiKey: process.env.NEXT_PUBLIC_AIRTABLE_READONLY_KEY });
[nit pick] commented out code

2021-11-16 02:21 UTC, narbs91 commented on src/components/ResourceCard/index.tsx
> +      <VStack w={{ base: '100%', sm: '30em', md: '300px' }}>
ah i see, you can try using the vertical height and width units instead (i find they work better):  `vh` and `vw` respectively.  So `50vw` would mean half the windows width

2021-11-16 02:57 UTC, gjsyme commented on src/types/airtable.ts
> +    'Developer DAO Member': boolean;
if you mean the content of 'fields' it's due to having to match the capitalized / spaced values coming off Airtable's API. otherwise, i might make an additional class to represent AirtableFields but didn't think it was necessry. i may very well be wrong.

2021-11-17 17:42 UTC, gjsyme commented
Last iteration: update dhaiwat dependency and resolve the common.json conflict.

2021-11-18 08:54 UTC, Dhaiwat10 commented
Think we can merge this in. Looking good

2021-11-18 08:55 UTC, Dhaiwat10 commented
We can, of course, have the design guild have a look at this later and get some design iterations going.

2021-11-20 02:12 UTC, narbs91 commented
@with-heart @codingwithmanny Do we want to keep this PR?  This is actually something educational and aligns with the direction of the DAO.  Plus @gjsyme, @Dhaiwat10 and @Neumand have done a decent bit of work to get it to where it's at.

CC: @kempsterrrr

2021-11-25 17:33 UTC, codingwithmanny commented
@narbs91 kind of feel this could be put on hold, because some of it _MAY_ translate to the new website.

2021-11-25 20:09 UTC, Dhaiwat10 commented
@narbs91 @codingwithmanny I think if we redesign this to be in-line with the new design scheme of the website, we can merge this in. In fact, we definitely want to have this on our website.

2021-11-25 20:12 UTC, narbs91 commented
Yeah that's what my thinking around it was too. The content fits the bill of what the DAO wants to push out , great learning sources.  We can probs keep it open for the moment and readjust when the simplified landing page is pushed out.

2022-05-03 13:30 UTC, closed without merging