Feature: Testnet local environment
Developer-DAO/developerdao.com pull request #162
Opened 2021-11-03 10:36 UTC by kavimaluskam

### What does it do?

Use environment based constants to point home page and direct mint to test-net on local developement.

### Any helpful background information?

- Move all hardcoded network configuration to `src/utils/DeveloperDaoConstants.ts`, which can be switched from main-net to test-net based on environment.
- Test case looks good.
- Updating homepage at the same time to make the `test-net` environment more in-sync.
- Updating footer link at the same time to make the `test-net` environment more in-sync.
- Only confusion is now `https://developerdao.vercel.app/` is still pointing to production / main-net environment.

### Any new dependencies? Why were they added?

`process.env.NODE_ENV`, controls most network related constants in `src/utils/DeveloperDaoConstants.ts`.

### Relevant screenshots/gifs

<img width="1320" alt="Screenshot 2021-11-03 at 11 32 12 AM" src="https://user-images.githubusercontent.com/19992414/140045200-7e8bce75-85db-44b6-8d85-123cc8d77a64.png">
<img width="792" alt="Screenshot 2021-11-03 at 11 32 29 AM" src="https://user-images.githubusercontent.com/19992414/140045210-e5a57f15-02bc-4242-a99c-2940ec81f903.png">

### Does it close any issues?

Focusing on issue #155 

Closes #...

2021-11-03 13:24 UTC, with-heart approved these changes

2021-11-03 13:24 UTC, with-heart commented on src/components/DirectMint/DirectMint.tsx
> +      )}
I feel like it'd be more clear to combine these two related cases together:

```tsx
{
  networkError && (
    <Text color="red">
      {t(
        NODE_ENV === 'development'
          ? 'ethereumDevNetworkPrompt'
          : 'ethereumNetworkPrompt',
      )}
    </Text>
  )
}
```

2021-11-03 13:24 UTC, with-heart commented on src/utils/DeveloperDaoConstants.ts
> +    : 'https://rinkeby.etherscan.io/tx/';
This is not really related to your PR but seeing this makes me feel like we should start using the [Next.js Environment Variables feature](https://nextjs.org/docs/basic-features/environment-variables) because most of these aren't constants.

2021-11-03 13:25 UTC, with-heart commented
> Only confusion is now https://developerdao.vercel.app/ is still pointing to production / main-net environment.

I'm not sure we have a good way around this with Vercel. Preview deploys are meant to mimic prod, not to be a test env.

2021-11-03 13:46 UTC, kavimaluskam commented on src/utils/DeveloperDaoConstants.ts
> +    : 'https://rinkeby.etherscan.io/tx/';
Yeah this would even be more clear.

2021-11-03 13:56 UTC, kavimaluskam commented
> > Only confusion is now https://developerdao.vercel.app/ is still pointing to production / main-net environment.
> 
> I'm not sure we have a good way around this with Vercel. Preview deploys are meant to mimic prod, not to be a test env.

I think it's good to have Vercel preview to be mimic prod, just the current https://developerdao.vercel.app/ is showing another version / website 👀 
<img width="952" alt="Screenshot 2021-11-03 at 2 54 41 PM" src="https://user-images.githubusercontent.com/19992414/140073363-26106735-5e88-4625-b248-083f24721f47.png">

2021-11-03 14:12 UTC, with-heart commented
OH I misread that URL! I was thinking it was our site's vercel URL, not the separate app.

2021-11-03 22:08 UTC, kavimaluskam commented
> OH I misread that URL! I was thinking it was our site's vercel URL, not the separate app.

I'd have provide more context for this.

The https://developerdao.vercel.app/ is referring to the TOKEN_FINDER_URL in direct mint page. Which looks to be pointing to another application by @tfmoliveira, providing list of available IDs. 

Maybe we shall discuss if we'd provide a similar functionality and replace the standalone application? 👀

2021-11-04 02:05 UTC, narbs91 requested changes

2021-11-04 02:05 UTC, narbs91 commented on src/components/DirectMint/DirectMint.tsx
>        providerOptions,
So overall things look great testing with MetaMask; however, in the case of walletConnect that won't work with the current setup if there's no NEXT_PUBLIC_INFURA_ID set up on the developers machine.  So let's do a couple of things before we wrap up this PR:

1.  Let's add a sample.env file to the root of the project and have it look just like this
```javascript
NEXT_PUBLIC_INFURA_ID=''
```
2.  Add a blurb in the `Developing` section of the readme that people who are testing/building blockchain related features to connect with MetaMask as a first option (as that doesn't require a infura_id).  If they want to test via walletConnect then they have to create an infura account themselves and add their personal infura_id to a .env file they create based on the sample we provide.  I'm also ok with not mentioning the walletConnect part at all and steer blockchain interaction testing towards MetaMask (though that might detract from adding more ways to connect through various providers in the future).

2021-11-04 02:11 UTC, narbs91 commented
Also looks like we're having a failure with the directMinting e2e test fyi

2021-11-04 02:56 UTC, codingwithmanny commented on src/utils/DeveloperDaoConstants.ts
> +    : 'https://rinkeby.etherscan.io/tx/';
Yeah I'm leaning towards more and more for the ENV vars because for the GitHub Actions, we're going to need to change almost everything to fit that scenario.

Thoughts on maybe a placeholder in the meantime:

```js
const DEVELOPER_DAO_CONTRACT = process.env.DEVELOPER_DAO_CONTRACT || (NODE_ENV === 'production'
    ? '0x25ed58c027921E14D86380eA2646E3a1B5C55A8b'
    : '0xbf114c4cbb4e70e6098589a918c84292cb40602a');
```

2021-11-04 12:49 UTC, kavimaluskam commented on src/utils/DeveloperDaoConstants.ts
> +    : 'https://rinkeby.etherscan.io/tx/';
Actually I prefer ENV VARs for as well. I think env variables is now very common for secrets and setting configuration for application with docker, cloud instance, and CI. 

Happy to do the change to use env var, but probably need to involve someone with vercel access.

2021-11-04 12:51 UTC, kavimaluskam commented on src/components/DirectMint/DirectMint.tsx
>        providerOptions,
Aw yeah I've forgot the testing about walletConnect. 

Thinking shall we complete the update to use ENV in this PR?

2021-11-04 13:07 UTC, with-heart commented on src/utils/DeveloperDaoConstants.ts
> +    : 'https://rinkeby.etherscan.io/tx/';
> While certainly possible to do I would argue that the typical usage for env variables that i've seen is usually towards storing secrets; however, even that is probably better served using a secrets manager TBH.

That's funny! My experience has been sort of the opposite. Env vars stored in checked-in files like `.env.development` are usually for differing URLs and such, with secrets being stored as env vars in something like Vercel's env var secrets manager.

2021-11-04 13:18 UTC, kavimaluskam commented on src/components/DirectMint/DirectMint.tsx
>        providerOptions,
And kinda curious how NEXT_PUBLIC_INFURA_ID is currently setup in the production enviornment? 🤔

2021-11-04 14:25 UTC, codingwithmanny commented on src/utils/DeveloperDaoConstants.ts
> +    : 'https://rinkeby.etherscan.io/tx/';
@with-heart samesies

> > While certainly possible to do I would argue that the typical usage for env variables that i've seen is usually towards storing secrets; however, even that is probably better served using a secrets manager TBH.
> 
> That's funny! My experience has been sort of the opposite. Env vars stored in checked-in files like `.env.development` are usually for differing URLs and such, with secrets being stored as env vars in something like Vercel's env var secrets manager.

2021-11-04 14:26 UTC, codingwithmanny commented on src/components/DirectMint/DirectMint.tsx
>        providerOptions,
Agree with @narbs91 

@kavimaluskam like as in the admin dashboard or how it exposes the env vars?

> And kinda curious how NEXT_PUBLIC_INFURA_ID is currently setup in the production enviornment? 🤔

2021-11-04 14:30 UTC, kavimaluskam commented on src/components/DirectMint/DirectMint.tsx
>        providerOptions,
@codingwithmanny so there is one production `NEXT_PUBLIC_INFURA_ID` in vercel ?

And i am not very familiar with INFURA_ID, is it like some SDK ID? Can we have one for development ?

2021-11-04 14:32 UTC, codingwithmanny commented on src/components/DirectMint/DirectMint.tsx
>        providerOptions,
@kavimaluskam Technically anyone can sign up for one, and I think we're using someone's 🤷 .

I have to go through the process again, but the site is https://infura.io.

I believe it would work as the same process as signing up for an etherscan API key, it just allows you to do specific types of calls to contracts that would normally be done in your browser with metamask (even then there's a rate limit).

2021-11-04 15:27 UTC, kavimaluskam commented on src/utils/DeveloperDaoConstants.ts
> +    : 'https://rinkeby.etherscan.io/tx/';
It sounds good for me as well! Just generally means ENV is a good shit.

2021-11-04 15:54 UTC, kavimaluskam commented
Just added an env. var. approach.

2021-11-05 15:58 UTC, narbs91 commented on src/components/DirectMint/DirectMint.tsx
>        providerOptions,
Sorry i got to this a little late but just for clarity @kavimaluskam there is a `NEXT_PUBLIC_INFURA_ID` env variable set up in vercel with a valid (at least for now hehe) infura_id.  Since that env variable isn't available for local builds of the app we want to have people set their own variable (i.e. in a .env file) and populate it with their own infura_id like Manny explained above.  Infura itself is a cloud provider for Ethereum nodes (and i think IPFS too but don't remember) so that people can easily connect to the blockchain without having to setup a node themselves

2021-11-05 17:20 UTC, kavimaluskam commented on src/components/DirectMint/DirectMint.tsx
>        providerOptions,
Cool! @narbs91 
Have added a line in the README to ask for using `.env.development` for the `NEXT_PUBLIC_INFURA_ID`.

The `NEXT_PUBLIC_INFURA_ID` is missing in `.env.production`, thinking if it can be overrided by Vercel ENV?

2021-11-06 05:16 UTC, narbs91 requested changes
Looks like we're really close to closing this out after this last round of feedback @kavimaluskam ! Great stuff 👌

2021-11-06 05:16 UTC, narbs91 commented on src/components/DirectMint/DirectMint.tsx
> +    if (chainId === NETWORK_ID) {
So we actually have to change this condition slightly since `NETWORK_ID` is actually a string and not a number:
```javascript
 if (chainId.toString() === NETWORK_ID) {
      return true;
    }
```

2021-11-06 05:16 UTC, narbs91 commented on src/utils/DeveloperDaoConstants.ts
> +  process.env.NEXT_PUBLIC_DEVELOPER_DAO_CONTRACT ||
You actually don't need the extra conditionals here since you have specified a `env.development` which will be the profile that'll be loaded when someone runs `yarn dev`.  I would say it should be fine to remove these fallbacks

2021-11-06 05:16 UTC, narbs91 commented on .env.development
> +NEXT_PUBLIC_DEVELOPER_DAO_CONTRACT=0xbf114c4cbb4e70e6098589a918c84292cb40602a
So i ended up adding these key/values in vercel in two flavours:  one set for development/preview and another for production.  I re-ran the deploy job and it ended up picking up the env.development variables on the preview deploy (yay!) which solves our test vs prod issue.  So what that'll mean is that we can actually test minting on the preview builds against rinkeby and leave production as is with the legit minting

2021-11-06 05:16 UTC, narbs91 commented on .env.development
> +NEXT_PUBLIC_OPENSEA_DIRECT_LINK_PREFIX=https://testnets.opensea.io/assets/$DEVELOPER_DAO_CONTRACT
Can you switch `$DEVELOPER_DAO_CONTRACT` at the end here with the actual contract as I don't know if vercel can interpolate env variables like that

2021-11-06 05:16 UTC, narbs91 commented on .env.production
> +NEXT_PUBLIC_OPENSEA_DIRECT_LINK_PREFIX=https://testnets.opensea.io/assets/$DEVELOPER_DAO_CONTRACT
Same comment as above here

2021-11-06 14:59 UTC, kavimaluskam commented on .env.development
> +NEXT_PUBLIC_OPENSEA_DIRECT_LINK_PREFIX=https://testnets.opensea.io/assets/$DEVELOPER_DAO_CONTRACT
I think it's handled by Next.js? 
https://nextjs.org/docs/basic-features/environment-variables

But yeah, maybe it's better to make a full string in vercel and make both .env and vercel consistent.

2021-11-07 04:51 UTC, narbs91 requested changes

2021-11-07 04:51 UTC, narbs91 commented on src/utils/DeveloperDaoConstants.ts
> +  process.env.NEXT_PUBLIC_DEVELOPER_DAO_CONTRACT;
So the build seems to be failing complaining about this potentially not being a string, let's add `as string` to the end of these to make typescript happy

2021-11-07 04:51 UTC, narbs91 commented on src/components/DirectMint/DirectMint.tsx
> +    if (chainId === NETWORK_ID) {
Reminder that this still has to be done to get things to connect properly

2021-11-07 04:51 UTC, narbs91 commented on .env.production
> +NEXT_PUBLIC_ETHERSCAN_TX_URL=https://rinkeby.etherscan.io/tx/
These guys are still point to their respective test urls, let's change these to point to their prod counter parts

2021-11-07 13:08 UTC, kavimaluskam commented on src/components/DirectMint/DirectMint.tsx
> +    if (chainId === NETWORK_ID) {
Oh I've missed it, fixed.

2021-11-07 13:15 UTC, kavimaluskam commented on README.md
> +5. To test Walletconnect functionality, copy `.env.development` to `.env.local` and fill in your `INFURA_ID`.
sure updated.

2021-11-08 01:23 UTC, narbs91 commented
Great stuff @kavimaluskam !  So looks like we have fully functional Rinkeby minting on our preview/per-commit builds 🥳 .  I've added the remaining production environment variables to Vercel so we should be good to go after you resolve your conflicts with the master branch

2021-11-08 18:35 UTC, kavimaluskam commented
@narbs91 looks the new `useDevNFTSupply` is not working in testnet 🤔 let me look into this.

2021-11-08 18:41 UTC, kavimaluskam commented
@narbs91 Solved and updated the `useDevNFTSupply` with testnet functionality 👍

2021-11-09 01:49 UTC, narbs91 approved these changes
YAY!  Awesome work @kavimaluskam this is really going to help us out in the long term when we're developing blockchain oriented features with a legit "stagging"/"int" environment

2021-11-09 01:49 UTC, merged

2021-11-09 01:51 UTC, kavimaluskam commented
Thanks for your help on this PR mates 🎉🎉