responsive navbar
Developer-DAO/developerdao.com pull request #169
Opened 2021-11-05 00:38 UTC by theprojectcode

**Navbar is responsive now. Photos below show the navbar menu becoming responsive at smaller breakpoints.   ** 
Let me know if how my code looks. Would love feedback

<img width="667" alt="Screen Shot 2021-11-04 at 7 20 28 PM" src="https://user-images.githubusercontent.com/88997637/140438007-23144a5a-c1d7-45ec-8e0a-6e7be30c80e7.png">

<img width="668" alt="Screen Shot 2021-11-04 at 7 20 40 PM" src="https://user-images.githubusercontent.com/88997637/140438029-b05ce146-7da2-4caa-82b9-19fc7a0b3f81.png">

2021-11-05 04:21 UTC, theprojectcode commented
I realize that both of my build test failed. It looks like it failed because of the aioutline icon. Not sure why? I have it as a package.

2021-11-05 12:28 UTC, Neumand commented
@theprojectcode 

Maybe try running `npm i react-icons`? I don't see it in the package.json. Or you could use an icon from the `@chakraui/icons` package as I see that's already installed!

2021-11-05 13:21 UTC, with-heart commented
Let's go with `react-icons` for the time being! That gives us access to a much larger set of icons than `@chakra-ui/icons`.

Also welcome to open source @theprojectcode! ❤️ 

@allcontributors please add @theprojectcode for code

2021-11-05 13:54 UTC, with-heart commented
Also since we're using `yarn` in this project, be sure to use `yarn add react-icons` :)

2021-11-05 14:35 UTC, with-heart requested changes
This is a great first contribution! I noticed some differences between the original design and this new one though, so I left a few comments explaining what changed and how we can fix it. 

Happy to pair and work through the requested changes if need be!

2021-11-05 14:35 UTC, with-heart commented on src/components/Nav/index.tsx
> +          </Flex>
Changing the way we used `Link` here made it so "Developer DAO" isn't part of the link, so we can't click it to return to the homepage. Only the logo works as a link.

We can safely revert this part to what it was previously and it'll still work fine.

```tsx
        <Link href="/" passHref>
          <HStack as="a" title={t('title')} display="flex" alignItems="center">
            <Logo h={7} w={7} />
            <chakra.span
              fontWeight="bold"
              fontSize="sm"
              color="gray.600"
              transition="color 300ms ease-in-out"
              _hover={{ color: 'black' }}
            >
              {t('title')}
            </chakra.span>
          </HStack>
        </Link>
```

2021-11-05 14:35 UTC, with-heart commented on src/components/Nav/index.tsx
> +              />
Looks like we missed the part of the code that makes this a link! 😆 

```suggestion
            <chakra.a
              href="https://github.com/Developer-DAO/developer-dao"
              target="_blank"
              rel="noreferrer"
              title={t('daoGithubRepo')}
            >
              <IconGitHub
                h={7}
                w={7}
                opacity={0.6}
                transition="opacity 300ms ease-in-out"
                _hover={{ opacity: 1 }}
              />
            </chakra.a>
```

2021-11-05 14:35 UTC, with-heart commented on src/components/Nav/index.tsx
> +                pb={7}
Just fyi! Chakra has a shortcut syntax that handles `pt` and `pb` at the same time: `py`

So `py={7}`. Not worth changing, just something to be aware of!

There's also `px` that handles `pl`+`pr`

2021-11-05 14:35 UTC, with-heart commented on src/components/Nav/index.tsx
> +              color="brand.500"
We should replace these props with the original:

```suggestion
              spacing={{ base: 3, sm: 10 }}
```

2021-11-05 15:09 UTC, theprojectcode commented
> This is a great first contribution! I noticed some differences between the original design and this new one though, so I left a few comments explaining what changed and how we can fix it.
> 
> Happy to pair and work through the requested changes if need be!

Hey man, thanks for the feedback. I'd love to pair and work through those things as well. Let's set up a time.

2021-11-05 15:10 UTC, theprojectcode commented
> > This is a great first contribution! I noticed some differences between the original design and this new one though, so I left a few comments explaining what changed and how we can fix it.
> > Happy to pair and work through the requested changes if need be!
> 
> Hey man, thanks for the feedback. I'd love to pair and work through those things as well. Let's set up a time.

@with-heart

2021-11-16 12:45 UTC, with-heart approved these changes

2021-11-17 04:22 UTC, narbs91 approved these changes
LGTM!  Awesome stuff gang love the collaboration/team-work that happened here!  Congrats @theprojectcode for grinding through the trials of learning React, well done!

2021-11-17 13:23 UTC, theprojectcode commented
Thank you! @narbs91 I couldn't have done it without @with-heart thank you guys for your support!

2021-11-17 18:47 UTC, merged