Reduce site to README style with missions, values, and goals
Developer-DAO/developerdao.com pull request #198
Opened 2021-11-24 16:39 UTC by with-heart

Hey yall! 👋 

# What?

This PR replaces the existing pages on https://developerdao.com with a simplified `README`-style design that displays: 

- Season 0 status update
- mission, values, and goals from our [Season 0 Snapshot](https://snapshot.org/#/devdao.eth/proposal/0x52fc76fe5865cf038b89b8c6ef78b6e691c0ab9c2b1228b84b0813b7832ce369)
- social network links
- Vercel sponsorship

![developer-dao-1ub0ssa7o-developdao vercel app_ (1)](https://user-images.githubusercontent.com/1954752/143278630-fdb3eeb1-62fc-44d6-a372-a9418c381503.png)

![developer-dao-1ub0ssa7o-developdao vercel app_](https://user-images.githubusercontent.com/1954752/143278648-bcc81a2d-c3a7-47fc-806f-3aa184a4dea8.png)

_For some reason Chrome DevTools isn't rendering the Vercel logo next to "Powered by" in the footer. Trust me, it's there._

# Why?

The existing pages are almost entirely focused on the DEV token. With all tokens minted, this direction for the site is no longer relevant to us as an organization. Instead what we need now from the site is the ability to publicly define ourselves and our brand.

To make the site brand-driven, you need a brand. To make a brand, you need product and design working in unison. Luckily, we have a design guild that's doing exactly that! So ownership of the site has moved to the design guild.

However, those things take a not-_right now_ amount of time while we need _right now_ the site to represent our mission, values, and goals. 

So this PR is an attempt to balance those two concerns by giving us a page that meets our _right now_ needs in a manner that is [_easy to delete_](https://programmingisterrible.com/post/139222674273/how-to-write-disposable-code-in-large-systems) due to minimal stylistic and design choices.

This is basically the TL;DR for why. If you want to read more about my thinking here see the [Why, Continued](#why-continued) section.

# How?

My primary goal for this PR was to implement something that is easy to modify and easy to delete. Easy to modify so we can make changes to this if needed while design guild is still getting things together, and easy to delete so that when design guild is ready to get started there's minimal effort required to undo these changes.

- A single-file page with three components
- Minimal design choices, with font size adjustments, vertical spacing, and the callout section being the only real complexities

# Dear Reviewers

If you're looking to review this PR, here are some potential ways to get involved:

- share feedback & suggestions about the design
- ask questions about the way this was implemented
- test responsiveness of the page

---

# Why, Continued

This PR was difficult for me to write for a number of reasons. I think it's important for me to explain what those reasons are to give you an idea of the kinds of things I'm thinking about as a guild "leader" and open source maintainer.

To do that, let's start with the story of `developerdao.com`!

## How we got here

When the DAO first started, we obviously didn't have a website.

Once a bunch of developers joined the DAO, we started to build ourselves a site. We quickly coalesced around the concept of minting DEV tokens.

![image](https://user-images.githubusercontent.com/1954752/143136744-da3201ff-c0bc-43ca-926b-48570730001b.png)

We created a landing page which displayed tokens as images and allowed users to view tokens by number.

We created a projects page which listed member-created projects related to the token.

We created a minting experience that allowed users to connect their wallet and mint a token straight from our site!

Lots of cool stuff!

But then we hit a wall: there were no more tokens left to mint.

![image](https://user-images.githubusercontent.com/1954752/143137143-1dc5a26f-bd25-43c1-88e1-71bf7f0d3d7e.png)

An exciting wall at least! However, this presented a problem for the DAO: the public face of our organization is filled with content related to achieving a goal we no longer have, and nothing related to our brand or future plans.

Fuck.

## Where we're going

With the start of Season 0, the intent is to move ownership of the site from developers to designers (The Design Guild®).

Rather than developers owning the process and determining the site's content, we're letting the design guild take the reins so they can establish a visual identity for our public face.

![image](https://user-images.githubusercontent.com/1954752/143266506-a44a7c40-fc50-4343-b29c-fadba274818c.png)

However this overly simplifies the picture. What does it mean for design guild to own the site? What does their process look like? Probably something like this:

![image](https://user-images.githubusercontent.com/1954752/143267340-bd705a72-d5ae-486a-98e2-d94520d789d1.png)

That's a lot of things! That's a lot of time!

And it's made even worse by the fact that the design guild has a significant work load, and currently doesn't have enough designers to handle it all.

So what do we do about the site _right now_?

Our brand (for now) primarily consists of our mission, values, and goals. This PR takes those pieces and offers a minimal implementation of the brand-driven direction we're hoping to move in.

This is the starting point for what I view as our path forward:

![image](https://user-images.githubusercontent.com/1954752/143270059-8fe7e63f-d5a2-4b0d-ad17-d73c2ec4fdfc.png)

## So if I have some idea of a plan, why was this difficult?

1. As an open source maintainer, I feel uncomfortable essentially "blowing away" a bunch of existing work by other people and replacing it with something the community didn't build together.
2. The whole point of moving ownership to the design guild is to escape the "devs doing dev stuff" problem, where developers are setting priorities and implementing things in the space where our brand should be represented, and yet here we are with this PR: a dev doing dev stuff in the brand space.
3. This comes uncomfortably close to a top-down declaration of "this is what we're doing now", which is the opposite of the bottom-up leadership style I've spent most of my time in the DAO trying to encourage.

## So what?

The reason I wanted to talk about all this and note why it was difficult for me is because I think **being genuine** is _the most important thing_ in communicating with each other.

Normally a PR like this would feel _wrong_ to me in so many ways. And yet here I am, opening this PR and proposing it to the community anyway.

It's my hope that by being genuine and open with my thoughts and feelings, you'll come away from this PR thinking _with-heart wouldn't do this unless he felt that it was **very important** for our organization_.

2021-11-24 17:07 UTC, with-heart commented on src/pages/index.tsx
> +};
If you haven't seen the `children` pattern before, it's something unique (I think) to React. 

`children` refers to the child elements of the component when rendered. So in this case, by setting `icon` to `children`, it means we render the component's icon like this:

```tsx
<SocialIconLink href="https://discord.gg/devdao" label="Discord">
  <FaDiscord />
</SocialIconLink>
```

`children` refers to the `<FaDiscord />` line.

It's a useful little pattern that makes for cleaner component APIs.

2021-11-24 17:07 UTC, with-heart commented on src/theme.ts
>    },
This block increases the font sizes in our Chakra system. My eyes are 33 years old and it's hard for me to read tinyass text. There is also a sizable minority of humans with vision problems, so larger text makes the web more accessible for them.

This is a preference decision and can easily be rolled back later based on design guild's direction, but since it's currently nothing but text, I think it's safe for us to bet on an increase in readability.

2021-11-25 04:13 UTC, narbs91 commented on src/pages/index.tsx
> +            <SocialIconLink
For these icon based links, let's make it a bit easier for someone whose hard of sight to figure out what they landed on.  If the screen reader lands on this element it will just read out that it's on a link but not announce where the link leads.  To get by this issue, the most common remedy is to introduce a hidden piece of text that doesn't show up on the UI but will be picked up by a screen reader.  The trick is to apply a special css class that looks like this:

```css
.visuallyhidden {
  clip: rect(0, 0, 0, 0);
  clip-path: inset(50%);
  height: 1px;
  width: 1px;
  padding: 0;
  overflow: hidden;
  position: absolute !important;
  white-space: nowrap;
}
```

We can define this in a global css file so it's available everywhere and can be re-used as the website evolves.  To actually get this to work, you can add something like this in between the socialIconLink:

```javascript
<SocialIconLink href="https://discord.gg/devdao" label="Discord">
              <FaDiscord />
             <span className={visuallyhidden}>
                Opens the Developer DAO Discord in a new window
              </span>
 </SocialIconLink>
```

That span will be hidden on the UI but be read if a screen reader lands on the link.   Let me know if you have any questions if something doesn't make sense or needs better clarification

2021-11-25 04:15 UTC, narbs91 commented on src/pages/index.tsx
> +      {shouldShowIcon && <Icon as={GiCrownedHeart} boxSize={20} />}
Is there a reason behind why we would want to hide the icon?

2021-11-25 04:19 UTC, narbs91 commented on cypress/integration/nft-search.spec.js
> +describe.skip('NFT Search', () => {
We should also probs skip some of the relevant unit tests as well

2021-11-25 04:22 UTC, narbs91 commented
The "Read our snapshot" button looks to be misbehaving on iPhone screen sizing:  

![image](https://user-images.githubusercontent.com/29411347/143379331-1523b6ca-23a4-4a79-8176-3eac2b9664ad.png)

2021-11-25 15:15 UTC, with-heart commented on src/pages/index.tsx
> +      {shouldShowIcon && <Icon as={GiCrownedHeart} boxSize={20} />}
Good question! I had originally made it so the icon appeared above the content in smaller screens, but looking at it on my phone made me realize that it was mostly just a waste of vertical space.

2021-11-30 19:21 UTC, etr2460 approved these changes
one main comment about the vercel logo, not sure if it was actually addressed already (judging from the screenshots). from my perspective it seems fine to ship this and iterate, but i'm coming in without full context

2021-11-30 19:21 UTC, etr2460 commented on src/pages/index.tsx
> +                src="/vercel-logotype-light.svg"
in the screenshot, it looked like this was still the black version of the logo, so it wasn't visible

2021-11-30 19:21 UTC, etr2460 commented on src/pages/index.tsx
> +            <SocialIconLink
i'm not an a11y expert, but wouldn't setting the `label` to `Link to our Discord community`/`Link to our official Twitter` be sufficient? this label gets applied as the `aria-label` in the SocialIconLink component, so i would've thought it was enough

2021-12-01 19:08 UTC, with-heart commented on src/pages/index.tsx
> +            <SocialIconLink
@etr2460 I thought that too but it seems like that may not be the case! https://gomakethings.com/revisting-aria-label-versus-a-visually-hidden-class/

2021-12-01 19:14 UTC, with-heart commented on cypress/integration/nft-search.spec.js
> +describe.skip('NFT Search', () => {
I think we can delete those in a follow-up PR! I disabled the e2e tests because they were running in ci but apparently we aren't running the unit tests in ci

2021-12-01 19:16 UTC, with-heart commented on src/pages/index.tsx
> +                src="/vercel-logotype-light.svg"
Yeah I haven't figured out why the logo looks wrong in the screenshot. It's definitely the correct color in the `svg` and in the deployed output.

I think it might be a bug with the Chrome DevTools tbh

2021-12-01 21:14 UTC, embiem requested changes
Loving the simplicity and focus on a11y ❤️

2021-12-01 21:14 UTC, embiem commented on public/locales/en/common.json
> +    "body1": "Onboard, Education, & Support Web3 Developers",
```suggestion
    "body1": "Onboard, Educate & Support Web3 Developers",
```

2021-12-01 23:58 UTC, codingwithmanny commented on src/pages/index.tsx
> +          </Stack>
```suggestion
          </Stack>
          <Stack spacing={6}>
            <Heading as="h2" fontSize="lg">
              {t('links.title')}
            </Heading>
            <UnorderedList spacing={3}>
              <ListItem><a href="https://developerdao.notion.site/developerdao/Developer-DAO-Wiki-eff4dcb00bef46fbaa93e9e4cf940e2e">{t('links.wiki')}</a></ListItem>
              <ListItem><a href="https://forum.developerdao.com">{t('links.forum')}</a></ListItem>
              <ListItem><a href="https://snapshot.org/#/devdao.eth">{t('links.snapshot')}</a></ListItem>
            </UnorderedList>
          </Stack>
```

2021-12-02 00:02 UTC, codingwithmanny commented on public/locales/en/common.json
> +  },
```suggestion
  },
  "links": {
    "title": "Useful links",
    "wiki": "Wiki",
    "forum": "Forum",
    "snapshot": "Snapshot",
  },
```

2021-12-02 00:36 UTC, narbs91 commented on src/pages/index.tsx
> +            <SocialIconLink
Yes, unfortunately screen readers don't all work the same.  While the label approach my work for one it doesn't really work for all.  The hidden text though works on a wider range (maybe all?) screen readers and is the preferred approach.

2021-12-02 00:37 UTC, narbs91 commented on cypress/integration/nft-search.spec.js
> +describe.skip('NFT Search', () => {
Yeah, i don't think we ever configured it even though i think we were planning too.  All good :)

2021-12-02 00:44 UTC, narbs91 approved these changes

2021-12-02 01:37 UTC, with-heart commented on src/pages/index.tsx
> +          </Stack>
You're a wizard

2021-12-02 01:42 UTC, merged