Add Footer component
Developer-DAO/developerdao.com pull request #211
Opened 2022-02-25 22:22 UTC by joneskj55

### What does it do?
Adds new footer component

### Any helpful background information?
[Discord Chat](https://discord.com/channels/883478451850473483/884852584941232169/946474631760601098)

### Any new dependencies? Why were they added?
No

### Relevant screenshots/gifs
![Screen Shot 2022-02-25 at 4 13 49 PM](https://user-images.githubusercontent.com/20748598/155810643-0096107d-550b-4b4c-9007-b4651a5beaeb.png)

![Screen Shot 2022-02-25 at 4 13 54 PM](https://user-images.githubusercontent.com/20748598/155810664-c059faea-53e4-4872-956a-f76dadbcd8ef.png)

![Screen Shot 2022-02-25 at 4 14 13 PM](https://user-images.githubusercontent.com/20748598/155810671-da45e0ec-3433-4cb6-88a8-b815eb0c3243.png)

![Screen Shot 2022-02-25 at 4 14 27 PM](https://user-images.githubusercontent.com/20748598/155810681-9b3cec0f-38f5-4120-a9f3-0935e82d24f2.png)

### Does it close any issues?

Closes #206

2022-03-05 10:08 UTC, Nazeeh21 requested changes
`Footer` should occupy the full width of the website.
I've already added `paddingY` in the `Layout` component, so it don't require adding more padding to the components

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56908732/156878465-c51c3671-ef59-48d3-92b7-c42a4ecda9f2.png">

Also, the responsiveness of the component needs to be approved, right now it doesn't seem responsive for screen sizes less than 800px 

<img width="601" alt="image" src="https://user-images.githubusercontent.com/56908732/156878721-0974948e-2a32-480d-b0da-c6132706937f.png">

2022-03-05 10:08 UTC, Nazeeh21 commented on src/Components/Footer/index.tsx
> +      <Container as={Stack} maxW={'6xl'} py={10}>
`Footer` should occupy the full width of the website.
I've already added `paddingY` in the `Layout` component, so it don't require adding more padding to the components

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56908732/156878465-c51c3671-ef59-48d3-92b7-c42a4ecda9f2.png">

2022-03-05 10:08 UTC, Nazeeh21 commented on src/Components/Footer/index.tsx
> +      <Container as={Stack} maxW={'6xl'} py={10}>
I think removing this `Container` will fix this

2022-03-16 06:30 UTC, Nazeeh21 commented
Hey @joneskj55, just tag me here when you feel PR is ready for review, thanks

2022-03-17 16:19 UTC, joneskj55 commented on src/Components/Footer/index.tsx
> +      <Container as={Stack} maxW={'6xl'} py={10}>
Footer now spans full width

2022-03-17 16:20 UTC, joneskj55 commented on src/Components/Footer/index.tsx
> +      <Container as={Stack} maxW={'6xl'} py={10}>
👍🏾

2022-03-17 16:21 UTC, joneskj55 commented
Hi, @Nazeeh21 please review at your convenience. Thanks.

2022-03-19 07:51 UTC, Nazeeh21 commented
Thanks @joneskj55, will review it soon 😊

2022-03-21 18:28 UTC, joneskj55 commented
@Nazeeh21 Awesome, and thanks for the assist as well!

2022-03-24 10:36 UTC, Nazeeh21 commented
https://user-images.githubusercontent.com/56908732/159897800-14851102-6b4a-4c53-b84a-c3f37707bd78.mov

@joneskj55 I think we need to work on reducing the gap between the **useful links**, **discover** and **social** as on screen size between 750 to 1074, D_D heading and **useful links** is getting overlapped. You can see it in the video I attached

2022-03-24 18:17 UTC, joneskj55 commented
Aahh good catch! @Nazeeh21 I'll get on this ASAP.

2022-03-26 18:44 UTC, joneskj55 commented
Uploading Screen Recording 2022-03-26 at 1.39.16 PM.mov…

@Nazeeh21 I think that Vercel deployment may be a commit behind. I haven't made any changes and running the project locally I am getting what's shown in this attached video.

2022-03-29 22:09 UTC, Nazeeh21 commented
Ohh is it? I'll test it out tomorrow locally and everything works fine, we'll just merge it once we authorize the vercel. Thanks for your patience

2022-03-30 06:15 UTC, Nazeeh21 commented
@joneskj55 I tested out the PR locally and it's amazing and I think ready to be merged, once we've vercel deployment to these.

2022-04-02 19:47 UTC, merged