initial commit
Developer-DAO/developerdao.com pull request #213
Opened 2022-02-28 10:55 UTC by andreivdev

### Status

**Work in progress**

- [x] Initial layout and commit
- [ ] Fonts
- [ ] Sizes, margins and padding
- [ ] "After launching $CODE" layout and easy method to switch between layouts

### What does it do?

Adds Intro component

### Relevant screenshots/gifs

![Screenshot 2022-02-28 at 12 50 37](https://user-images.githubusercontent.com/8058187/155970826-25392476-831d-4bda-a69f-2eae9eb6a99a.png)

![Screenshot 2022-02-28 at 12 51 03](https://user-images.githubusercontent.com/8058187/155970838-6adf9dde-29ee-4ebc-bfcb-35f0b3803c8b.png)

### Does it close any issues?

Closes #208

2022-03-01 03:44 UTC, Nazeeh21 commented
Closes #208

2022-03-01 03:57 UTC, Nazeeh21 reviewed
Overall, it looks good, and some of the changes were suggested. Nothing else, just try to synchronize with the design as much as possible.

2022-03-01 03:57 UTC, Nazeeh21 commented on src/Components/Intro/index.tsx
> +              <Image src="/lightning_1.svg" alt="snapshot" />
Instead of using the SVG from the public folder, lets use the `BsFillLightningChargeFill` svg from the [react-icons](https://react-icons.github.io/react-icons/search?q=light) library and remove the svg from the `public` folder. This will help us in keeping our website fast

2022-03-01 03:57 UTC, Nazeeh21 commented on src/Components/Intro/index.tsx
> +      <Flex direction="row" flexWrap="wrap" justifyContent="space-between">
```<Flex direction="row" width="100%" flexWrap="wrap" justifyContent="space-between">```

2022-03-09 10:45 UTC, Nazeeh21 commented
LMK, when its ready for review, thanks!

2022-03-19 12:39 UTC, andreivdev commented
> LMK, when its ready for review, thanks!

ready 🚀 

sorry for the delay :(

2022-03-20 02:01 UTC, Nazeeh21 commented
No worries, will soon review it today.

2022-03-21 17:41 UTC, Nazeeh21 requested changes
@andreivdev the component is not responsive and is not synchronizing with the figma design.

https://user-images.githubusercontent.com/56908732/159331562-5c8d4941-9c0e-4059-8fe0-5c173eeb2cf4.mov

**Read our snapshot** button should be aligned on the left instead of the right

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56908732/159332112-6b4245db-3c81-4a45-9156-68fa096c1bdf.png">

size of the intro images should be large and should synchronize with the Figma designs and also vertically align in one line.

LMK if you want my help on this, thanks

2022-03-21 18:18 UTC, andreivdev commented
Hmmmm

I can't reproduce your screenshot. 

![Screenshot 2022-03-21 at 20 17 20](https://user-images.githubusercontent.com/8058187/159338225-55f2c8d1-44b1-4df7-9c07-d05078caeb9d.png)

Can you maybe authorise Vercel so I can look at that?

2022-03-21 18:31 UTC, Nazeeh21 commented
> Hmmmm
> 
> I can't reproduce your screenshot.
> Can you maybe authorise Vercel so I can look at that?

I don't have the access to the vercel. @with-heart can you please authorize vercel to deploy this PR?

2022-03-24 10:31 UTC, Nazeeh21 commented
> Hmmmm
> 
> I can't reproduce your screenshot.
> Can you maybe authorise Vercel so I can look at that?

@andreivdev vercel has deployed this PR, so I think now you will be able to reproduce it?

2022-04-16 19:36 UTC, Nazeeh21 commented
I don't think we require this now. Thanks @andreivdev  for the hard work and for doing considerable work in the Intro section and getting this component done.

2022-04-16 19:36 UTC, closed without merging